version: '3.4'

services:

  develenv:
    build:
      context: .
      target: build
    environment:
      PRODUCT_VERSION: ${PRODUCT_VERSION:-0.0}
      PRODUCT_REVISION: ${PRODUCT_REVISION:-0}
      HOST_UID_GID: ${HOST_UID_GID:-}
      DOCKER_HOST: ${DOCKER_HOST:-}
    entrypoint: tail -f /dev/null
    depends_on:
      - server

  server:
    image: ${DOCKER_IMAGE:-server}
    build:
      context: .
      args:
        PRODUCT_VERSION: ${PRODUCT_VERSION:-0.0}
        PRODUCT_REVISION: ${PRODUCT_REVISION:-0}
    environment: 
      MONGO_HOST: mongo:27017
      MAPON_KEY: ${MAPON_KEY}
    restart: always
    depends_on: 
      - mongo
    
  mongo:
    image: mongo:4.4.4
    environment: 
      MONGO_INITDB_DATABASE: mapon
