package dao

// Generated by https://quicktype.io

type Car struct {
	Data CarData `json:"data"`
}

type CarData struct {
	Units []CarUnit `json:"units"`
}

type CarUnit struct {
	UnitID             int64              `json:"unit_id"`
	BoxID              int64              `json:"box_id"`
	CompanyID          int64              `json:"company_id"`
	CountryCode        string             `json:"country_code"`
	Label              string             `json:"label"`
	Number             string             `json:"number"`
	Shortcut           string             `json:"shortcut"`
	VehicleTitle       interface{}        `json:"vehicle_title"`
	CarRegCertificate  string             `json:"car_reg_certificate"`
	Vin                string             `json:"vin"`
	Type               string             `json:"type"`
	Icon               string             `json:"icon"`
	Lat                float64            `json:"lat"`
	Lng                float64            `json:"lng"`
	Direction          int64              `json:"direction"`
	Speed              interface{}        `json:"speed"`
	Mileage            int64              `json:"mileage"`
	LastUpdate         string             `json:"last_update"`
	IgnitionTotalTime  int64              `json:"ignition_total_time"`
	State              State              `json:"state"`
	MovementState      State              `json:"movement_state"`
	FuelType           string             `json:"fuel_type"`
	AvgFuelConsumption AvgFuelConsumption `json:"avg_fuel_consumption"`
	CreatedAt          string             `json:"created_at"`
}

type AvgFuelConsumption struct {
	Norm        int64  `json:"norm"`
	Measurement string `json:"measurement"`
}

type State struct {
	Name      string     `json:"name"`
	Start     string     `json:"start"`
	Duration  int64      `json:"duration"`
	DebugInfo *DebugInfo `json:"debug_info,omitempty"`
}

type DebugInfo struct {
}
