package dao

import "time"

// Generated by https://quicktype.io

// Route (autogenerated type)
type Route struct {
	Data *RouteData `json:"data"`
}

// RouteData (autogenerated type)
type RouteData struct {
	Units []*RouteUnit `json:"units"`
}

// RouteUnit (autogenerated type)
type RouteUnit struct {
	UnitID int64           `json:"unit_id"`
	Routes []*RouteElement `json:"routes"`
}

// RouteElement (autogenerated type)
type RouteElement struct {
	Type     UnitType `json:"type"`
	RouteID  int64    `json:"route_id"`
	Start    Point    `json:"start"`
	End      *Point   `json:"end,omitempty"`
	AvgSpeed *int64   `json:"avg_speed,omitempty"`
	MaxSpeed *int64   `json:"max_speed,omitempty"`
	Distance *int64   `json:"distance,omitempty"`
}

// Point (autogenerated type)
type Point struct {
	Time    time.Time `json:"time"`
	Address *string   `json:"address,omitempty"`
	Lat     *float64  `json:"lat,omitempty"`
	Lng     *float64  `json:"lng,omitempty"`
}

// UnitType (autogenerated type)
type UnitType string

// Enumerated values for UnitType (autogenerated type)
const (
	Stop      UnitType = "stop"
	TypeRoute UnitType = "route"
)
